repos:
  # Sync uv lockfile
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.14
    hooks:
      - id: uv-lock

  # Ruff linter & formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  # # Mypy static type checker
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.1
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports"]
